'use strict';

const CLASS_JEDI = {
  key: 'jedi',
  name: 'Jedi',
  description: 'O Jedi combina treinamento físico com o domínio da Força. Os Jedi concentram-se nas virtudes em combate, na defesa, e no treinamento com sabre-de-luz. Eles também são os embaixadores da Ordem Jedi, protegendo a República de todos os perigos. Poucos são fortes o bastante na Força e possuem a devoção necessária para seguir o caminho Jedi, mas esses poucos são recompensados com uma poderosa aliada.',
  hitDie: 10,
  startingHP: 30,
  trainedSkillsBase: 2,
  defenseBonus: { fort: 1, ref: 1, will: 1 },
  baseAttack: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
  classSkills: ['acrobatics','know1','know2','know3','know4','initiative','mechanics','perception','pilot','jump','endurance','useTheForce'],
  startingFeats: [
    'Sensitivo à Força',
    'Proficiência com Armas (Sabres-de-luz)',
    'Proficiência com Armas (Armas Simples)',
  ],
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent', 'lightsaber'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent', 'constructLightsaber'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Ataque Acrobático', 'Treinamento na Força', 'Defesas Aprimoradas',
    'Defesa Corpo-a-Corpo', 'Ataque Poderoso', 'Saque Rápido', 'Foco em Perícia', 'Treinamento em Perícia',
    'Foco em Arma (sabres-de-luz)', 'Maestria com Duas Armas I', 'Maestria com Duas Armas II',
    'Maestria com Duas Armas III', 'Trespassar', 'Trespassar Aprimorado',
  ],
  talentTrees: [
    {
      key: 'jediConsular',
      name: 'Árvore de Talentos do Cônsul Jedi',
      description: 'Os Jedi que seguem o caminho do cônsul são negociadores e embaixadores habilidosos. Você prefere usar a força de suas palavras e a sabedoria que a Força concede para resolver conflitos.',
      talents: [
        {
          id: 'skillfulAdvisor',
          name: 'Conselheiro Habilidoso',
          description: 'Você pode gastar uma ação de rodada completa aconselhando um aliado, dessa forma você concede a ele um bônus de +5 em seu próximo teste de perícia. Se você gastar um Ponto da Força, esse bônus aumenta para +10. O alvo precisa ser capaz (e estar disposto) a ouvir e compreender seus conselhos. Você não pode aconselhar a si mesmo. Esse é um efeito de afetar a mente.',
          prerequisites: [],
        },
        {
          id: 'expertNegotiator',
          name: 'Negociador Especialista',
          description: 'Utilizando uma ação padrão, você pode enfraquecer a determinação de um inimigo com suas palavras. O alvo precisa ter um valor de Inteligência de 3 ou maior e precisa ser capaz de ver, ouvir e compreender você. Faça um teste de Persuasão; se o resultado igualar ou exceder a Defesa de Vontade do alvo, ele cai 1 passo em seu marcador de condição. O alvo ganha um bônus de +5 em sua Defesa de Vontade se for de nível maior que você. Se o alvo alcançar a condição final de seu marcador, ele não irá cair inconsciente; ao invés disso, ele não poderá atacar você ou seus aliados pelo resto do encontro, a menos que você ou um de seus aliados ataque-o ou os aliados dele. Esse é um efeito de afetar a mente.',
          prerequisites: [],
        },
        {
          id: 'forcePersuasion',
          name: 'Persuasão da Força',
          description: 'Você pode usar seu modificador da perícia Usar a Força ao invés de seu modificador da perícia Persuasão quando realizar testes de Persuasão. Você é considerado treinado na perícia Persuasão. Se você estiver habilitado a fazer uma nova jogada de um teste de Persuasão, você pode, ao invés disso, fazer uma nova jogada de seu teste de Usar a Força (sujeito às mesmas circunstâncias e limitações).',
          prerequisites: ['expertNegotiator'],
        },
        {
          id: 'masterNegotiator',
          name: 'Negociador Mestre',
          description: 'Se você for bem sucedido ao usar o talento Negociador Especialista, seu alvo cai um passo adicional no seu marcador de condição, totalizando 2 passos negativos. Este é um efeito de afetar a mente.',
          prerequisites: ['expertNegotiator'],
        },
      ],
    },
    {
      key: 'jediGuardian',
      name: 'Árvore de Talentos do Guardião Jedi',
      description: 'Os Jedi que seguem o caminho do guardião são mais voltados para o combate que outros Jedi, afiam suas habilidades para se tornarem combatentes mortais.',
      talents: [
        {
          id: 'elusiveTarget',
          name: 'Alvo Elusivo',
          description: 'Quando estiver lutando corpo-a-corpo com um ou múltiplos oponentes, outros oponentes que tentarem acertar você com ataques à distância receberão uma penalidade de -5. Essa penalidade se acumula com a penalidade normal por atirar em combate corpo-a-corpo, tornando a penalidade por tentar acertá-lo em -10.',
          prerequisites: [],
        },
        {
          id: 'forceIntuition',
          name: 'Intuição da Força',
          description: 'Você pode usar seu modificador da perícia Usar a Força ao invés de seu modificador da perícia Iniciativa quando realizar testes de Iniciativa. Você é considerado treinado na perícia Iniciativa. Se você estiver habilitado a fazer uma nova jogada de um teste de Iniciativa, você pode, ao invés disso, fazer uma nova jogada de seu teste de Usar a Força (sujeito às mesmas circunstâncias e limitações).',
          prerequisites: [],
        },
        {
          id: 'battleMeditation',
          name: 'Meditação de Batalha',
          description: 'A técnica Jedi conhecida como Meditação de Batalha permite que você e seus aliados trabalhem juntos, em harmonia, e num nível de precisão que só pode se dar através da Força. Utilizando uma ação de rodada completa, você pode gastar 1 Ponto da Força para conferir a você e todos os seus aliados em até 6 quadrados +1 de bônus de competência nas jogadas de ataque que permanece até o final do encontro. Aliados beneficiados precisam permanecer em até 6 quadrados de você para manter o bônus, e o perdem se você ficar inconsciente ou morrer. Esse é um efeito de afetar a mente.',
          prerequisites: ['forceIntuition'],
        },
        {
          id: 'acrobaticRecovery',
          name: 'Recuperação Acrobática',
          description: 'Se um efeito fizer com que você caia prostrado, você pode realizar um teste de Acrobacia contra ND 20 para permanecer em pé.',
          prerequisites: [],
        },
        {
          id: 'resilient',
          name: 'Resiliente',
          description: 'Você pode gastar uma ação de rodada completa para subir dois passos no seu marcador de condição.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'jediSentinel',
      name: 'Árvore de Talentos do Sentinela Jedi',
      description: 'Os Jedi que seguem o caminho do sentinela são os verdadeiros inimigos do Lado Negro, pois, onde quer que vão caçam o mal e lutam para impedir que a escuridão se espalhe. Você é um mestre da sutileza e é difícil de ser tentado pelo Lado Negro, mesmo quando é constantemente confrontado pelo seu poder.',
      talents: [
        {
          id: 'senseDarkSide',
          name: 'Sentir o Lado Negro',
          description: 'Os Jedi que seguem o caminho do sentinela se tornam excepcionalmente capazes de expurgar o mal. Você pode fazer uma nova jogada de qualquer teste de Usar a Força feito para sentir a presença e relativa localização de um personagem com um Valor do Lado Negro de 1 ou maior. Você deve usar o resultado da nova jogada, mesmo que seja pior que o da primeira.',
          prerequisites: [],
        },
        {
          id: 'resistDarkSide',
          name: 'Resistir ao Lado Negro',
          description: 'Você ganha +5 de bônus da Força em todos seus valores de Defesa contra poderes da Força que tenham o descritor [Lado Negro] e poderes da Força originados de qualquer usuário do Lado Negro da Força (ou seja, qualquer usuário da Força que tenha um Valor do Lado Negro igual ao seu valor de Sabedoria).',
          prerequisites: ['senseDarkSide'],
        },
        {
          id: 'clearMind',
          name: 'Limpar a Mente',
          description: 'Você pode fazer uma nova jogada de qualquer teste resistido de Usar a Força feito para evitar ser detectado por outros usuários da Força. Você deve usar o resultado da nova jogada, mesmo que seja pior que o da primeira.',
          prerequisites: ['senseDarkSide'],
        },
        {
          id: 'forceMist',
          name: 'Névoa da Força',
          description: 'Você pode gastar um Ponto da Força como uma ação padrão para criar uma "névoa" que esconderá você e seus aliados da percepção de outros. Você pode esconder um número de criaturas em sua linha de visão igual ao seu nível de classe. Faça um teste de Usar a Força e compare o resultado com a Defesa de Vontade de qualquer oponente que se mova para a linha de visão de qualquer das criaturas escondidas. Se seu teste ultrapassar a Defesa de Vontade do oponente, todas as criaturas são tratadas como se possuíssem camuflagem total contra esse oponente. A Névoa da Força permanecerá por até 1 minuto, mas será dissipada instantaneamente se qualquer um que estiver escondido por ela fizer um ataque.',
          prerequisites: ['clearMind'],
        },
        {
          id: 'darkSideFoe',
          name: 'Flagelo do Lado Negro',
          description: 'Contra criaturas com um Valor do Lado Negro de 1 ou maior, você causa dano extra nos ataques corpo-a-corpo igual ao seu bônus de Carisma (mínimo de +1).',
          prerequisites: ['senseDarkSide'],
        },
      ],
    },
    {
      key: 'lightsaberCombat',
      name: 'Árvore de Talentos do Combate com Sabre-de-Luz',
      description: 'O sabre-de-luz é a arma preferida pelo Jedi. Não sendo desajeitado ou aleatório como um blaster, o sabre-de-luz é uma arma elegante para um combatente mais civilizado. Os seguintes talentos permitem a você aprimorar suas proezas realizadas com um sabre-de-luz.',
      talents: [
        {
          id: 'block',
          name: 'Bloquear',
          description: 'Como uma reação, você pode neutralizar um ataque corpo-a-corpo ao ser bem sucedido num teste de Usar a Força. O ND para o teste de perícia é igual ao resultado obtido na jogada do ataque que deseja neutralizar, e você recebe uma penalidade cumulativa de -5 em seu teste de Usar a Força para cada vez que tenha usado o talento Bloquear ou Defletir desde o começo de seu turno passado. Você precisa ter um sabre-de-luz em mãos e ativado para usar este talento, e precisa estar ciente do ataque e não pode estar surpreendido. Você pode gastar um Ponto da Força para usar este talento para neutralizar um ataque contra um personagem adjacente.',
          prerequisites: [],
        },
        {
          id: 'deflect',
          name: 'Defletir',
          description: 'Como uma reação, você pode neutralizar um ataque à distância ao ser bem sucedido num teste de Usar a Força. O ND para o teste de perícia é igual ao resultado obtido na jogada do ataque que deseja neutralizar, e você recebe uma penalidade cumulativa de -5 em seu teste de Usar a Força para cada vez que tenha usado o talento Bloquear ou Defletir desde o começo de seu turno passado. Você precisa ter um sabre-de-luz em mãos e ativado para usar este talento, e precisa estar ciente do ataque e não pode estar surpreendido. Você pode gastar um Ponto da Força para usar este talento para neutralizar um ataque contra um personagem adjacente.',
          prerequisites: ['block'],
        },
        {
          id: 'throwLightsaber',
          name: 'Arremessar Sabre-de-Luz',
          description: 'Você pode arremessar um sabre-de-luz utilizando uma ação padrão, tratando-o como uma arma de arremesso (sem este talento, um sabre-de-luz arremessado é considerado uma arma de arremesso improvisada). Você é considerado proficiente em arremessar o sabre-de-luz, e aplica as penalidades normais por alcance na jogada de ataque. O sabre-de-luz arremessado causa o dano normal da arma se acertar. Se o alvo não estiver afastado de você mais do que 6 quadrados, você pode retornar seu sabre-de-luz para suas mãos utilizando uma ação rápida ao fazer um teste de Usar a Força contra um ND 20.',
          prerequisites: [],
        },
        {
          id: 'lightsaberDefense',
          name: 'Defesa com Sabre-de-Luz',
          description: 'Utilizando uma ação rápida, você pode usar seu sabre-de-luz para aparar ataques de seus oponentes, recebendo +1 de bônus de deflexão em sua Defesa de Reflexos até o começo de seu próximo turno. Você precisa ter um sabre-de-luz em mãos e ativado para usar este talento, e não ganha o bônus de deflexão se estiver surpreendido ou não estiver ciente dos ataques. Você pode escolher este talento mais de uma vez; cada vez que o selecionar, o bônus de deflexão aumenta em +1 (máximo de +3).',
          prerequisites: [],
          multiSelect: true,
          maxSelect: 3,
        },
        {
          id: 'lightsaberSpecialization',
          name: 'Especialização em Arma (Sabres-de-Luz)',
          description: 'Você recebe +2 de bônus nas jogadas de dano proveniente de ataque corpo-a-corpo com sabre-de-luz.',
          prerequisites: [],
          requiresFeat: 'Foco em Arma (sabres-de-luz)',
        },
        {
          id: 'redirectShot',
          name: 'Redirecionar Disparo',
          description: 'Uma vez por rodada, quando você for bem sucedido em defletir um disparo de blaster com o talento Defletir, você pode fazer imediatamente um ataque à distância contra outro alvo que esteja em sua linha de visão. Aplique as penalidades normais na jogada de ataque, não levando em conta a distância que o disparo percorreu para "atingir" você. Se o ataque for bem sucedido, ele causa o dano normal da arma no alvo. Apenas simples disparos de blaster podem ser redirecionados dessa maneira.',
          prerequisites: ['deflect'],
          requiresBab: 5,
        },
      ],
    },
  ],
};
