'use strict';

const CLASS_JEDI_KNIGHT = {
  key: 'jediKnight',
  name: 'Cavaleiro Jedi',
  prestige: true,
  description: 'Entre os Jedi, àqueles que se provam capazes, sábios, autossuficientes e estáveis é dado o título de Cavaleiro. Confiados a ensinar aprendizes e executar missões com pouco suporte, são os guardiões da galáxia.',
  prereqs: {
    bab: 7,
    trainedSkills: ['useTheForce'],
    feats: ['Sensitivo à Força', 'Proficiência com Armas (Sabres-de-luz)'],
    notes: ['Deve ter construído seu próprio sabre-de-luz', 'Deve ser membro da tradição Jedi'],
  },
  hitDie: 10,
  startingHP: 10,
  trainedSkillsBase: 0,
  defenseBonus: { fort: 2, ref: 2, will: 2 },
  baseAttack: [1,2,3,4,5,6,7,8,9,10],
  classSkills: ['acrobatics','initiative','know1','know2','know3','know4','mechanics','perception','pilot','jump','endurance','useTheForce'],
  startingFeats: [],
  levelFeatures: {
    1:  ['defenseBonus', 'talent'],
    2:  ['forceTechnique'],
    3:  ['talent'],
    4:  ['forceTechnique'],
    5:  ['talent'],
    6:  ['forceTechnique'],
    7:  ['talent'],
    8:  ['forceTechnique'],
    9:  ['talent'],
    10: ['forceTechnique'],
  },
  bonusFeatList: [],
  talentTrees: [
    {
      key: 'duelist',
      name: 'Árvore de Talentos do Duelista',
      description: 'Através de rigoroso treinamento e experiência, você se tornou um dos maiores espadachins da galáxia.',
      talents: [
        { id: 'greaterWeaponFocusLightsaber', name: 'Foco em Arma Maior (sabres-de-luz)', description: 'Você recebe +1 nas jogadas de ataque corpo-a-corpo com sabres-de-luz. Acumula com a aptidão Foco em Arma (sabres-de-luz).', prerequisites: [], requiresFeat: 'Foco em Arma (sabres-de-luz)' },
        { id: 'amputatingAttack', name: 'Ataque Amputador', description: 'Quando causar dano com sabre-de-luz igual ou maior que os PV atuais e o limite de dano do alvo (dano suficiente para matar), você pode causar metade do dano e fazer o alvo cair 1 passo no marcador de condição, amputando um braço ou perna (impondo -5 em testes de For/Des e penalidades de mobilidade). Recebe ainda +2 nas jogadas de dano corpo-a-corpo com sabres-de-luz (acumula com Especialização em Arma).', prerequisites: ['greaterWeaponFocusLightsaber'], requiresFeat: 'Foco em Arma (sabres-de-luz); Especialização em Arma (sabres-de-luz)' },
        { id: 'forceFortification', name: 'Fortificação da Força', description: 'Como reação, gaste um ponto da Força para neutralizar um acerto crítico obtido contra você, sofrendo dano normal ao invés do crítico. Pode gastar este ponto mesmo se já tiver gasto outro nesta rodada.', prerequisites: [] },
        { id: 'multiattackLightsaber', name: 'Proficiência em Ataques Múltiplos (sabres-de-luz)', description: 'Quando fizer múltiplos ataques com sabre-de-luz como ação de ataque total, você reduz a penalidade em 2. Selecionável várias vezes (redução adicional de 2 cada).', prerequisites: [], multiSelect: true },
      ],
    },
    {
      key: 'lightsaberForms',
      name: 'Árvore de Talentos dos Estilos com um Sabre-de-Luz',
      description: 'Você tem um conhecimento refinado das técnicas com um sabre-de-luz. Qualquer um pode usar um desses estilos, mas você teve a disciplina e paciência para se tornar um verdadeiro mestre.',
      talents: [
        { id: 'ataru', name: 'Ataru', description: 'Você pode adicionar seu bônus de Destreza (ao invés do de Força) nas jogadas de dano ao brandir um sabre-de-luz. Empunhando com as duas mãos, aplica o dobro do bônus de Destreza ao dano.', prerequisites: [] },
        { id: 'djemSo', name: 'Djem So', description: 'Uma vez por rodada, quando um oponente acertar você um ataque corpo-a-corpo, você pode gastar um ponto da Força como reação para fazer imediatamente um ataque contra esse oponente.', prerequisites: [] },
        { id: 'niman', name: 'Niman', description: 'Quando brandindo um sabre-de-luz, você recebe +1 em sua Defesa de Reflexos e Defesa de Vontade.', prerequisites: [] },
        { id: 'jarKai', name: "Jar'Kai", description: 'Quando usar o talento Defesa com Sabre-de-Luz, você recebe o dobro do bônus de deflexão normal na sua Defesa de Reflexos enquanto empunha dois sabres-de-luz.', prerequisites: ['niman'], requiresFeat: 'Defesa com Sabre-de-Luz' },
        { id: 'makashi', name: 'Makashi', description: 'Brandindo um único sabre-de-luz com uma mão, o bônus de deflexão do talento Defesa com Sabre-de-Luz aumenta em 2 (máximo de +5).', prerequisites: [], requiresFeat: 'Defesa com Sabre-de-Luz' },
        { id: 'juyo', name: 'Juyo', description: 'Uma vez por encontro, gaste um ponto da Força (ação rápida) para designar um inimigo em sua linha de visão. Pelo resto do encontro, você pode jogar novamente seu primeiro ataque em cada rodada contra esse oponente, usando o melhor resultado.', prerequisites: [], requiresFeat: 'Foco em Arma (sabres-de-luz); Especialização em Arma (sabres-de-luz)', requiresBab: 10 },
        { id: 'shien', name: 'Shien', description: 'Sempre que redirecionar um disparo de blaster defletido, você recebe +5 em sua jogada de ataque à distância.', prerequisites: [], requiresFeat: 'Defletir; Redirecionar Disparo' },
        { id: 'shiiCho', name: 'Shii-Cho', description: 'Ao usar os talentos Bloquear ou Defletir, você sofre apenas -2 de penalidade em seu teste de Usar a Força para cada tentativa anterior de bloquear/defletir desde seu turno passado.', prerequisites: [], requiresFeat: 'Bloquear; Defletir' },
        { id: 'sokan', name: 'Sokan', description: 'Você pode escolher 10 em testes de Acrobacia para dar cambalhotas mesmo quando distraído ou ameaçado. Cada quadrado ameaçado ou ocupado que percorrer dando cambalhotas conta apenas como 1 quadrado de movimento.', prerequisites: [], requiresFeat: 'Recuperação Acrobática' },
        { id: 'soresu', name: 'Soresu', description: 'Você pode jogar novamente um teste falho de Usar a Força ao usar os talentos Bloquear ou Defletir.', prerequisites: [], requiresFeat: 'Bloquear; Defletir' },
        { id: 'trakata', name: 'Trakata', description: 'Empunhando um sabre-de-luz, você pode gastar duas ações rápidas para fazer um teste de Dissimulação para fintar em combate (desligar e religar a lâmina rapidamente).', prerequisites: [], requiresFeat: 'Foco em Arma (sabres-de-luz); Especialização em Arma (sabres-de-luz)', requiresBab: 12 },
        { id: 'vaapad', name: 'Vaapad', description: 'Atacando com um sabre-de-luz, você obtém acerto crítico com um 19 ou 20 natural. Um 19 natural não é acerto automático; se obter 19 natural e ainda errar, você não obtém crítico.', prerequisites: ['juyo'], requiresFeat: 'Foco em Arma (sabres-de-luz); Especialização em Arma (sabres-de-luz)', requiresBab: 12 },
      ],
    },
  ],
};
