'use strict';

const CLASS_JEDI = {
  key: 'jedi',
  name: 'Jedi',
  hitDie: 10,
  startingHP: 30,
  trainedSkillsBase: 2,
  defenseBonus: { fort: 1, ref: 1, will: 1 },
  baseAttack: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
  classSkills: ['acrobatics','know1','know2','know3','know4','initiative','mechanics','perception','pilot','jump','endurance','useTheForce'],
  startingFeats: [
    'Force Sensitivity',
    'Weapon Proficiency (Lightsabers)',
    'Weapon Proficiency (Simple Weapons)',
  ],
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent', 'lightsaber'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent', 'constructLightsaber'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Acrobatic Strike', 'Force Boon', 'Force Training', 'Improved Defenses',
    'Melee Defense', 'Power Attack', 'Quick Draw', 'Skill Focus', 'Skill Training',
    'Weapon Focus (lightsabers)', 'Dual Weapon Mastery I', 'Dual Weapon Mastery II',
    'Dual Weapon Mastery III', 'Trespass', 'Trespass Improved',
  ],
  talentTrees: [
    {
      key: 'jediConsular',
      name: 'Jedi Consular Talent Tree',
      description: 'Jedi who follow the Consular path are skilled negotiators and ambassadors who prefer to use the Force and their words to resolve conflicts.',
      talents: [
        {
          id: 'skillfulAdvisor',
          name: 'Skillful Advisor',
          description: 'Once per round as a free action, advise an ally within line of sight, granting a competence bonus equal to your Use the Force modifier on their next skill check. Spend 1 Force Point to increase this bonus to +10. You cannot advise yourself. This is a mind-affecting effect.',
          prerequisites: [],
        },
        {
          id: 'expertNegotiator',
          name: 'Expert Negotiator',
          description: 'You can use your Use the Force modifier in place of your Persuasion modifier when making Persuasion checks for intimidation. You are considered trained in Persuasion for this purpose.',
          prerequisites: [],
        },
        {
          id: 'forcePersuasion',
          name: 'Force Persuasion',
          description: 'You may use your Use the Force modifier in place of your Persuasion modifier when attempting to change an attitude. If you are already trained in Persuasion, you may reroll and keep the better result.',
          prerequisites: ['expertNegotiator'],
        },
        {
          id: 'masterNegotiator',
          name: 'Master Negotiator',
          description: 'When you successfully use the Expert Negotiator talent, the target also falls 1 additional step on the condition track, beyond the normal effects.',
          prerequisites: ['expertNegotiator'],
        },
      ],
    },
    {
      key: 'jediGuardian',
      name: 'Jedi Guardian Talent Tree',
      description: 'Jedi who follow the Guardian path focus their skills toward battle and becoming powerful combatants.',
      talents: [
        {
          id: 'elusiveTarget',
          name: 'Elusive Target',
          description: 'When fighting one or more opponents in melee, any opponent trying to target you with a ranged attack takes a -5 penalty on the attack roll. This penalty stacks with normal cover and concealment penalties.',
          prerequisites: [],
        },
        {
          id: 'forceIntuition',
          name: 'Force Intuition',
          description: 'You may use your Use the Force modifier instead of your Initiative modifier when making Initiative checks. You are considered trained in Initiative for this purpose.',
          prerequisites: [],
        },
        {
          id: 'battleMeditation',
          name: 'Battle Meditation',
          description: 'As a standard action, spend 1 Force Point to allow you and all allies within 6 squares to work together in harmony. All allies within 6 squares gain a +1 Force bonus to attack rolls and skill checks. Allies must remain within 6 squares or lose the bonus. The effect lasts 1 minute, or until you fall unconscious or die.',
          prerequisites: ['forceIntuition'],
        },
        {
          id: 'acrobaticRecovery',
          name: 'Acrobatic Recovery',
          description: 'When you are knocked prone, make an Acrobatics check (DC 20) as a reaction to immediately stand without provoking attacks of opportunity. You must use the result of the new check even if it is worse.',
          prerequisites: [],
        },
        {
          id: 'resilient',
          name: 'Resilient',
          description: 'As a full-round action, move up 2 steps on the condition track.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'jediSentinel',
      name: 'Jedi Sentinel Talent Tree',
      description: 'Jedi who follow the Sentinel path are the true enemies of the dark side, rooting out evil wherever it hides.',
      talents: [
        {
          id: 'senseDarkSide',
          name: 'Sense the Dark Side',
          description: 'Whenever you encounter a character with a Dark Side Score of 1 or more, you may make a Use the Force check as a reaction to detect the dark side in that character. The DC equals the character\'s Dark Side Score. You must use the result of the new check even if it is worse.',
          prerequisites: [],
        },
        {
          id: 'resistDarkSide',
          name: 'Resist the Dark Side',
          description: 'You gain a +5 insight bonus to all your defense values against dark side Force powers, and against any Force power used by a dark side character (Dark Side Score equal to your Wisdom score or higher).',
          prerequisites: ['senseDarkSide'],
        },
        {
          id: 'clearMind',
          name: 'Clear Mind',
          description: 'You may reroll any Use the Force check made to resist being detected by other Force users. You must use the result of the new check even if it is worse.',
          prerequisites: ['senseDarkSide'],
        },
        {
          id: 'forceMist',
          name: 'Force Mist',
          description: 'As a standard action, spend 1 Force Point to create a "mist" that obscures you and your allies from the perception of others. You may conceal a number of creatures up to your class level. Make a Use the Force check; compare the result against the Will Defense of any creature that moves to sense the concealed creatures.',
          prerequisites: ['clearMind'],
        },
        {
          id: 'darkSideFoe',
          name: 'Dark Side Foe',
          description: 'Against creatures with a Dark Side Score of 1 or more, your melee attacks deal extra damage equal to your Charisma bonus (minimum +1). You must use the result of the new check even if it is worse.',
          prerequisites: ['senseDarkSide'],
        },
      ],
    },
    {
      key: 'lightsaberCombat',
      name: 'Lightsaber Combat Talent Tree',
      description: 'Advanced lightsaber techniques used by experienced Jedi warriors.',
      talents: [
        {
          id: 'block',
          name: 'Block',
          description: 'As a reaction, make a Use the Force check (DC equal to the melee attack roll) to negate the attack. No damage is dealt on a success. You must have your lightsaber in hand and active. You must be aware of the attack and cannot be flat-footed. Spend 1 Force Point to use this talent.',
          prerequisites: [],
        },
        {
          id: 'deflect',
          name: 'Deflect',
          description: 'As a reaction, make a Use the Force check (DC equal to the ranged attack roll) to negate the attack. On success, the shot is deflected harmlessly. You must have your lightsaber in hand and active. Spend 1 Force Point to use this talent.',
          prerequisites: ['block'],
        },
        {
          id: 'throwLightsaber',
          name: 'Throw Lightsaber',
          description: 'You can throw your lightsaber as a thrown weapon using a standard action. It is treated as a ranged weapon. Apply the normal penalties to the attack roll for range. You are considered proficient in throwing it. If the target is no more than 6 squares away, you can return it to your hand using a quick action (DC 20 Use the Force).',
          prerequisites: [],
        },
        {
          id: 'lightsaberDefense',
          name: 'Lightsaber Defense',
          description: 'As a standard action, take a defensive stance. You gain a +1 deflection bonus to Reflex Defense against your opponents\' attacks until the start of your next turn. You must have your lightsaber in hand and active, cannot be surprised, and cannot be flat-footed.',
          prerequisites: [],
        },
        {
          id: 'lightsaberSpecialization',
          name: 'Lightsaber Specialization',
          description: 'You gain a +2 bonus on damage rolls with lightsabers in melee. You can select this talent multiple times; each time adds +1 to the bonus (maximum +3).',
          prerequisites: [],
          requiresFeat: 'Weapon Focus (lightsabers)',
        },
        {
          id: 'redirectShot',
          name: 'Redirect Shot',
          description: 'When you successfully deflect a blaster bolt with the Deflect talent, you may immediately redirect it against any other target within line of sight. Make a ranged attack roll against the new target. Only simple blaster shots may be redirected this way.',
          prerequisites: ['deflect'],
          requiresBab: 5,
        },
      ],
    },
  ],
};
