'use strict';

/** @type {import('../src/types/game.js').ClassData} */
export const CLASS_NOBLE = {
  key: 'noble',
  name: 'Nobre',
  description: 'Os membros da classe nobre empregam sua inteligência e carisma naturais para trilhar seu caminho pela galáxia. Da verdadeira realeza aos oficialmente eleitos, comandantes militares a senhores do crime, comerciantes, mercadores, embaixadores, astros do holovídeo e magnatas de corporações influentes, os tipos de personagens que aparecem na classe nobre são variados e numerosos. Com um sorriso vencedor, uma língua afiada, uma poderosa mensagem, ou a promessa de cumprir seus compromissos, o nobre comanda com respeito, faz amigos, e inevitavelmente influencia as pessoas.',
  hitDie: 6,
  startingHP: 18,
  trainedSkillsBase: 6,
  defenseBonus: { fort: 0, ref: 1, will: 2 },
  baseAttack: [0,1,2,3,3,4,5,6,6,7,8,9,9,10,11,12,12,13,14,15],
  classSkills: ['ride','know1','know2','know3','know4','deception','initiative','gatherInfo','persuasion','pilot','treatInjury','useComputer'],
  startingFeats: [
    'Linguista',
    'Proficiência com Armas (Pistolas)',
    'Proficiência com Armas (Armas Simples)',
  ],
  startingFeatsNotes: {
    'Linguista': 'Você deve cumprir com os pré-requisitos desta aptidão (valor mínimo de Inteligência 13) para recebê-la.',
  },
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Acuidade com Armas', 'Cirurgia com Cibernéticos', 'Defender-se em Corpo-a-Corpo',
    'Especialista Cirúrgico', 'Foco em Perícia', 'Linguista', 'Treinamento em Perícia',
    'Proficiência com Armaduras (leves)', 'Proficiência com Armas (armas de combate corpo-a-corpo avançadas)',
    'Proficiência com Armas (Rifles)',
  ],
  talentTrees: [
    {
      key: 'influence',
      name: 'Árvore de Talentos da Influência',
      description: 'Uma das características mais fortes do nobre é sua habilidade de exercer uma influência sobre seus oponentes.',
      talents: [
        {
          id: 'presence',
          name: 'Presença',
          description: 'Você pode fazer um teste de Persuasão para intimidar uma criatura como uma ação padrão (ao invés de uma ação de rodada completa).',
          prerequisites: [],
        },
        {
          id: 'weakenResolve',
          name: 'Enfraquecer a Determinação',
          description: 'Uma vez por rodada, quando você causar dano igual ou maior que o Limite de Dano do alvo, faça um teste de Persuasão como uma ação livre; se o resultado desse teste igualar ou exceder a Defesa de Vontade do alvo, você o enche de terror, fazendo com que ele fuja de você em deslocamento máximo durante 1 minuto. O alvo para de fugir e volta a agir normalmente caso seja ferido. Este efeito é automaticamente anulado se o nível do alvo for igual ou maior que seu nível de personagem. Este é um efeito de afetar a mente.',
          prerequisites: ['presence'],
        },
        {
          id: 'weakenResolveImproved',
          name: 'Enfraquecer a Determinação Aprimorado',
          description: 'Como Enfraquecer a Determinação, exceto que agora o alvo não para de fugir caso seja ferido.',
          prerequisites: ['presence', 'weakenResolve'],
        },
        {
          id: 'demandSurrender',
          name: 'Exigir Rendição',
          description: 'Uma vez por encontro você pode fazer um teste de Persuasão utilizando uma ação padrão para exigir a rendição de um oponente que tenha tido seus pontos de vida reduzidos à metade ou menos do total. Se seu teste igualar ou exceder a Defesa de Vontade do alvo, ele se rende a você e seus aliados, largando qualquer arma que esteja segurando, e não faz nenhuma ação hostil. Se o alvo for de nível maior que você, ele recebe um bônus de +5 na Defesa de Vontade. Se você ou qualquer um de seus aliados atacarem o alvo, ele não se submeterá a sua vontade e poderá agir normalmente. Você só pode usar este talento contra o mesmo alvo uma vez por encontro. Este é um efeito de afetar a mente.',
          prerequisites: ['presence'],
        },
      ],
    },
    {
      key: 'inspiration',
      name: 'Árvore de Talentos da Inspiração',
      description: 'Os nobres são reconhecidos pela sua habilidade para inspirar seus seguidores e imbuí-los com grandeza. Você pode conseguir resultados de seus amigos, aliados e seguidores que outros líderes não conseguiriam. Todos os talentos desta árvore possuem efeitos de afetar a mente, e você não pode usá-los em si mesmo.',
      talents: [
        {
          id: 'bolsterAlly',
          name: 'Fortalecer Aliado',
          description: 'Utilizando uma ação padrão você pode fortalecer um aliado que esteja em sua linha de visão, fazendo-o subir um passo em seu marcador de condição e dando a ele um número de pontos de vida temporários igual ao nível de personagem dele se ele tiver metade ou menos do seu total de pontos de vida. O dano sofrido é subtraído primeiro dos pontos de vida temporários, e quaisquer pontos de vida temporários remanescentes ao final do encontro são perdidos. Você não pode fortalecer o mesmo aliado mais de uma vez em um mesmo encontro, e não pode fortalecer a si mesmo.',
          prerequisites: [],
        },
        {
          id: 'inciteZeal',
          name: 'Incitar Fervor',
          description: 'Toda vez que você acertar um oponente em um ataque corpo-a-corpo ou à distância você pode (como uma ação livre) escolher dar a um aliado que esteja em sua linha de visão um bônus no dano de seu próximo ataque igual ao nível de personagem dele. Uma vez que o fervor tenha sido incitado, o aliado afetado não precisa permanecer dentro de sua linha de visão; se ele errar o próximo ataque, ele perde o bônus concedido por este talento. Você não pode incitar fervor em si mesmo.',
          prerequisites: ['bolsterAlly', 'inspiringConfidence'],
        },
        {
          id: 'inspiringConfidence',
          name: 'Inspirar Confiança',
          description: 'Utilizando uma ação padrão, você pode inspirar confiança em todos os aliados que estejam dentro de sua linha de visão, concedendo a eles +1 de bônus de moral nas jogadas de ataque e +1 de bônus de moral nos testes de perícia pelo resto do encontro ou até que você fique inconsciente ou morra. Uma vez inspirados, seus aliados não precisam permanecer dentro de sua linha de visão. Você não pode inspirar confiança em si mesmo.',
          prerequisites: [],
        },
        {
          id: 'inspiringFervor',
          name: 'Inspirar Ardor',
          description: 'Toda vez que um aliado que esteja dentro de sua linha de visão realizar um ataque que faça cair em um passo o marcador de condição de um oponente (como por causar um dano que exceda o Limite de Dano do alvo), ele cai um passo negativo adicional.',
          prerequisites: ['bolsterAlly', 'inspiringConfidence', 'inciteZeal'],
        },
        {
          id: 'inspiringSpeed',
          name: 'Inspirar Rapidez',
          description: 'Utilizando uma ação rápida você pode encorajar um de seus aliados que se encontra dentro de sua linha de visão a realizar com rapidez um teste de perícia. No próximo turno desse aliado, ele pode fazer um teste de perícia que requeira uma ação padrão utilizando uma ação de movimento.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'leadership',
      name: 'Árvore de Talentos da Liderança',
      description: 'Como um líder nato, você sabe como liderar seus companheiros e seguidores rumo ao sucesso. Todos os talentos desta árvore são efeitos de afetar a mente, e você não pode usar nenhum destes talentos em si mesmo.',
      talents: [
        {
          id: 'bornLeader',
          name: 'Líder Nato',
          description: 'Uma vez por encontro, utilizando uma ação rápida, você concede a todos os aliados que estejam em sua linha de visão +1 de bônus de intuição nas jogadas de ataque. Este efeito permanece enquanto eles mantiverem a linha de visão com você. Um aliado perde este bônus imediatamente se a linha de visão com você for interrompida ou se você ficar inconsciente ou morrer.',
          prerequisites: [],
        },
        {
          id: 'coordinate',
          name: 'Coordenar',
          description: 'Quando usa este talento, utilizando uma ação padrão, todos os aliados que estiverem dentro de sua linha de visão recebem +1 de bônus adicional quando usarem uma ação de prestar auxílio até o começo do seu próximo turno. Você pode escolher este talento mais de uma vez; cada vez que o fizer, o bônus concedido pelo talento Coordenar aumenta em +1 (para um máximo de +5).',
          prerequisites: ['bornLeader'],
          multiSelect: true,
          maxSelect: 5,
        },
        {
          id: 'commandAtDistance',
          name: 'Comandar à Distância',
          description: 'Qualquer aliado que receber o benefício por seu talento Líder Nato não irá perder esse benefício se a linha de visão dele com você for interrompida.',
          prerequisites: ['bornLeader'],
        },
        {
          id: 'fearlessLeader',
          name: 'Líder Destemido',
          description: 'Utilizando uma ação rápida você pode se tornar um exemplo de coragem para seus aliados. Pelo resto do encontro, seus aliados recebem +5 de bônus de moral em suas Defesas de Vontade contra qualquer efeito de medo. Seus aliados perdem esse benefício se perderem a linha de visão com você, ou se você for morto ou ficar inconsciente.',
          prerequisites: ['bornLeader'],
        },
        {
          id: 'rallyTroops',
          name: 'Reorganizar as Tropas',
          description: 'Uma vez por encontro você pode reorganizar seus aliados e trazê-los de volta quando estiverem perto de serem derrotados. Utilizando uma ação rápida, qualquer aliado em sua linha de visão que esteja com metade do total de seus pontos de vida ganha +2 de bônus de moral em suas Defesas de Reflexos, Defesas de Vontade e +2 de bônus em todas as jogadas de dano pelo resto do encontro.',
          prerequisites: ['bornLeader', 'commandAtDistance'],
        },
      ],
    },
    {
      key: 'lineage',
      name: 'Árvore de Talentos da Linhagem',
      description: 'Você levou uma vida privilegiada e colhe os benefícios de uma educação e de uma condição financeira superiores à da maioria dos cidadãos da galáxia.',
      talents: [
        {
          id: 'connections',
          name: 'Conexões',
          description: 'Você está apto a obter equipamentos licenciados, restritos, militares ou ilegais sem ter que pagar a licença certificada ou ter que passar por um teste de antecedentes, desde que o custo total do equipamento desejado seja igual ou menor que seu nível de personagem ×1000 créditos. Além disso, quando tentar obter equipamento ou serviços pelo mercado negro, você reduz o multiplicador do custo no mercado negro em 1.',
          prerequisites: [],
        },
        {
          id: 'educated',
          name: 'Instruído',
          description: 'Graças à sua excelente educação você pode fazer qualquer teste da perícia Conhecimento sem treinamento.',
          prerequisites: [],
        },
        {
          id: 'wealthy',
          name: 'Riqueza',
          description: 'A cada vez que você recebe um nível (incluindo o nível no qual selecionou este talento), você recebe uma quantidade de créditos igual a 5000 × seu nível de classe. Você pode gastar esses créditos da maneira que desejar.',
          prerequisites: [],
        },
        {
          id: 'spontaneousAbility',
          name: 'Habilidade Espontânea',
          description: 'Uma vez por dia, você pode realizar um teste de uma perícia sem treinamento como se você fosse treinado nela. Exceção: você não pode usar este talento para realizar um teste sem treinamento de Usar a Força a menos que possua a aptidão Sensitivo à Força. Você pode selecionar este talento mais de uma vez; cada vez que fizer, você poderá utilizá-lo uma vez a mais por dia.',
          prerequisites: ['educated'],
          multiSelect: true,
        },
      ],
    },
  ],
};
