'use strict';

const CLASS_NOBLE = {
  key: 'noble',
  name: 'Noble',
  hitDie: 6,
  startingHP: 18,
  trainedSkillsBase: 6,
  defenseBonus: { fort: 0, ref: 1, will: 2 },
  baseAttack: [0,1,2,3,3,4,5,6,6,7,8,9,9,10,11,12,12,13,14,15],
  classSkills: ['ride','know1','know2','know3','know4','deception','initiative','gatherInfo','persuasion','pilot','treatInjury','useComputer'],
  startingFeats: [
    'Linguist',
    'Weapon Proficiency (Pistols)',
    'Weapon Proficiency (Simple Weapons)',
  ],
  startingFeatsNotes: {
    'Linguist': 'Requires Intelligence 13 to gain this feat.',
  },
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Acumen with Weapons', 'Surgery', 'Cybernetics Expertise', 'Improved Defenses', 'Skill Focus',
    'Combat Expertise', 'Acrobatic Attack', 'Double Attack', 'Quick Draw', 'Rapid Strike',
    'Skill Training', 'Weapon Proficiency (advanced melee)', 'Weapon Proficiency (rifles)',
    'Linguist', 'Mobility', 'Trespass', 'Trespass Improved',
  ],
  talentTrees: [
    {
      key: 'influence',
      name: 'Influence Talent Tree',
      description: 'One of the strongest characteristics of the noble is the ability to exert influence over others.',
      talents: [
        {
          id: 'presence',
          name: 'Presence',
          description: 'As a standard action (rather than a full-round action), you can make a Persuasion check to intimidate a creature as a standard action.',
          prerequisites: [],
        },
        {
          id: 'weakenResolve',
          name: 'Weaken Resolve',
          description: 'Once per round, when you deal damage equal to or greater than the target\'s Damage Threshold, make a Persuasion check as a free action. If the result equals or exceeds the target\'s Will Defense, the target flees from you at maximum speed for 1 minute. Spend 1 Force Point to add a +10 bonus to this check. This is a mind-affecting effect.',
          prerequisites: ['presence'],
        },
        {
          id: 'weakenResolveImproved',
          name: 'Weaken Resolve (Improved)',
          description: 'As Weaken Resolve, except the target cannot flee if it is injured. It is otherwise subject to all the normal effects of Weaken Resolve.',
          prerequisites: ['presence', 'weakenResolve'],
        },
        {
          id: 'demandSurrender',
          name: 'Demand Surrender',
          description: 'Once per encounter, as a standard action, make a Persuasion check to demand the surrender of a target with half or fewer total hit points remaining. If the result equals or exceeds the target\'s Will Defense, the target surrenders. This is a mind-affecting effect.',
          prerequisites: ['presence'],
        },
      ],
    },
    {
      key: 'inspiration',
      name: 'Inspiration Talent Tree',
      description: 'Nobles are renowned for their ability to inspire their followers and allies, imbuing them with greatness.',
      talents: [
        {
          id: 'bolsterAlly',
          name: 'Bolster Ally',
          description: 'As a standard action, move one ally within line of sight up 1 step on the condition track. Spend 1 Force Point to increase the effect. Temporary hit points granted this way are lost at the end of the encounter.',
          prerequisites: [],
        },
        {
          id: 'inciteZeal',
          name: 'Incite Zeal',
          description: 'Each time you hit an opponent with a melee or ranged attack, any ally within line of sight gains a bonus to damage equal to your class level on their next attack. This bonus lasts until the start of your next turn.',
          prerequisites: ['bolsterAlly', 'inspiringConfidence'],
        },
        {
          id: 'inspiringConfidence',
          name: 'Inspiring Confidence',
          description: 'As a standard action, grant all allies within line of sight a +1 morale bonus to attack rolls and a +1 morale bonus to skill checks until the end of the encounter. Once inspired, the ally does not need to remain within line of sight.',
          prerequisites: [],
        },
        {
          id: 'inspiringFervor',
          name: 'Inspiring Fervor',
          description: 'Each time an ally within line of sight makes an attack that reduces an opponent by 1 or more steps on the condition track, that ally gains a temporary morale bonus to damage equal to your class level until the start of your next turn.',
          prerequisites: ['bolsterAlly', 'inspiringConfidence', 'inciteZeal'],
        },
        {
          id: 'inspiringSpeed',
          name: 'Inspiring Speed',
          description: 'As a quick action, you can encourage one ally within line of sight to perform a skill check requiring a standard action as a move action on their next turn. The next round, that ally can make the required action using a move action instead.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'leadership',
      name: 'Leadership Talent Tree',
      description: 'As a born leader, you know how to lead your companions and followers toward success.',
      talents: [
        {
          id: 'bornLeader',
          name: 'Born Leader',
          description: 'Once per encounter as a quick action, grant all allies within line of sight a +1 morale bonus to attack rolls until the start of your next turn.',
          prerequisites: [],
        },
        {
          id: 'coordinate',
          name: 'Coordinate',
          description: 'As a standard action, grant all allies within line of sight a +1 competence bonus to a chosen skill until the end of the encounter. You can select this talent multiple times; each time, the bonus increases by +1 (maximum +5).',
          prerequisites: ['bornLeader'],
        },
        {
          id: 'commandAtDistance',
          name: 'Command at Distance',
          description: 'Any ally who receives the benefit of the Born Leader talent does not lose it if line of sight is interrupted.',
          prerequisites: ['bornLeader'],
        },
        {
          id: 'fearlessLeader',
          name: 'Fearless Leader',
          description: 'As a quick action, set an example of courage for your allies. All allies within line of sight receive a +5 morale bonus on their Will Defenses against fear effects until the start of your next turn.',
          prerequisites: ['bornLeader'],
        },
        {
          id: 'rallyTroops',
          name: 'Rally Troops',
          description: 'Once per encounter as a quick action, reorganize your allies when they are about to be routed. Using a quick action, any ally within line of sight that has half or fewer total hit points gains a +2 morale bonus to Reflex Defense, Fortitude Defense, and Will Defense and a +2 morale bonus to all attack rolls until the end of the encounter.',
          prerequisites: ['bornLeader', 'commandAtDistance'],
        },
      ],
    },
    {
      key: 'lineage',
      name: 'Lineage Talent Tree',
      description: 'You reap the benefits of a privileged upbringing and superior education and financial standing.',
      talents: [
        {
          id: 'connections',
          name: 'Connections',
          description: 'You are able to obtain licensed, restricted, or military equipment without needing to pay the certification fee or pass an antecedents test, as long as the total cost is equal to or less than your character level × 1000 credits.',
          prerequisites: [],
        },
        {
          id: 'educated',
          name: 'Educated',
          description: 'You can make any Knowledge skill check without training. You can select this talent multiple times; each time, you can use one more Knowledge skill without training.',
          prerequisites: [],
        },
        {
          id: 'wealthy',
          name: 'Wealthy',
          description: 'Each time you gain a level (including this one), you receive credits equal to 5000 × your character level. You can spend these credits freely.',
          prerequisites: [],
        },
        {
          id: 'spontaneousAbility',
          name: 'Spontaneous Ability',
          description: 'Once per day, you may make a skill check without training as if you were trained in it. Exception: you cannot use this talent to make Use the Force checks unless you have the Force Sensitivity feat.',
          prerequisites: [],
        },
      ],
    },
  ],
};
