'use strict';

export const CLASS_SCOUT = {
  key: 'scout',
  name: 'Batedor',
  description: 'Os batedores são exploradores e aventureiros naturais cheios de curiosidade e treinados para todo tipo de situação nos ambientes onde geralmente operam. Os batedores tendem a ser independentes, alistando-se onde os pagamentos são generosos e suas habilidades são melhores utilizadas e testadas. Eles sabem como reconhecer o perigo e localizar o básico necessário para a sobrevivência. O batedor busca conhecimento, tentando resolver mistérios, e procura ser sempre o primeiro a ver algo novo e diferente.',
  hitDie: 8,
  startingHP: 24,
  trainedSkillsBase: 5,
  defenseBonus: { fort: 1, ref: 2, will: 0 },
  baseAttack: [0,1,2,3,3,4,5,6,6,7,8,9,9,10,11,12,12,13,14,15],
  classSkills: ['ride','know1','know2','know3','know4','climb','stealth','initiative','mechanics','swim','perception','pilot','endurance','jump','survival'],
  startingFeats: [
    'Recuperação Rápida',
    'Proficiência com Armas (Pistolas)',
    'Proficiência com Armas (Rifles)',
    'Proficiência com Armas (Armas Simples)',
  ],
  startingFeatsNotes: {
    'Recuperação Rápida': 'Você deve cumprir com os pré-requisitos desta aptidão (valor mínimo de Constituição 13 e treinado na perícia Tolerância) para ganhá-la.',
  },
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Ataque em Movimento', 'Certeiro', 'Combate Veicular', 'Ataque Duplo', 'Defesas Aprimoradas',
    'Foco em Perícia', 'Linguista', 'Mobilidade', 'Proficiência com Armas (armas de combate corpo-a-corpo avançadas)',
    'Tiro Rápido', 'Trespassar', 'Trespassar Aprimorado', 'Tiro Preciso', 'Treinamento em Perícia',
  ],
  talentTrees: [
    {
      key: 'awareness',
      name: 'Árvore de Talentos da Consciência',
      description: 'Você é excepcionalmente bom em perceber coisas e evitar situações perigosas.',
      talents: [
        {
          id: 'sharpenedSenses',
          name: 'Sentidos Aguçados',
          description: 'Você pode fazer uma nova jogada de qualquer teste de Percepção, mas o resultado da nova jogada deve ser utilizado mesmo que seja pior.',
          prerequisites: [],
        },
        {
          id: 'improvedInitiative',
          name: 'Iniciativa Aprimorada',
          description: 'Você pode fazer uma nova jogada de qualquer teste de Iniciativa, mas o resultado da nova jogada deve ser utilizado mesmo que seja pior.',
          prerequisites: ['sharpenedSenses'],
        },
        {
          id: 'exceptionalDodgeI',
          name: 'Esquiva Excepcional I',
          description: 'Você mantém seu bônus de Destreza em sua Defesa de Reflexos mesmo se for flanqueado ou atacado por um inimigo escondido. Você ainda perde seu bônus de Destreza em sua Defesa de Reflexos se estiver imobilizado.',
          prerequisites: ['sharpenedSenses', 'improvedInitiative'],
        },
        {
          id: 'exceptionalDodgeII',
          name: 'Esquiva Excepcional II',
          description: 'Você não pode ser flanqueado. Você pode reagir a oponentes em ambos os lados facilmente, como se reagisse a um único atacante.',
          prerequisites: ['sharpenedSenses', 'improvedInitiative', 'exceptionalDodgeI'],
        },
        {
          id: 'experiencedTracker',
          name: 'Rastreador Experiente',
          description: 'Você não recebe penalidades nos testes de Sobrevivência feitos para seguir rastros quando estiver se movimentando utilizando seu deslocamento normal. Sem este talento você receberia uma penalidade de -5 nos testes de Sobrevivência feitos para seguir rastros quando estiver se movimentando no seu deslocamento normal.',
          prerequisites: ['sharpenedSenses'],
        },
      ],
    },
    {
      key: 'camouflage',
      name: 'Árvore de Talentos da Camuflagem',
      description: 'Você aprende como se mesclar rapidamente ao ambiente.',
      talents: [
        {
          id: 'improvedStealth',
          name: 'Furtividade Aprimorada',
          description: 'Você pode fazer uma nova jogada de qualquer teste de Furtividade, mas o resultado da nova jogada deve ser utilizado mesmo que seja pior.',
          prerequisites: [],
        },
        {
          id: 'concealedMovement',
          name: 'Movimento Encoberto',
          description: 'Você é muito bom em se esconder estando em movimento. Você não recebe penalidades em seu teste de Furtividade quando estiver se movimentando no seu deslocamento normal.',
          prerequisites: [],
        },
        {
          id: 'sharpshooting',
          name: 'Tiro Apurado',
          description: 'Você não recebe penalidade em sua jogada de ataque quando estiver atacando alvos com camuflagem (mas não camuflagem total).',
          prerequisites: ['improvedStealth'],
        },
        {
          id: 'totalCamouflage',
          name: 'Camuflagem Total',
          description: 'Em qualquer situação que lhe conceda camuflagem (de terreno, pouca luz, etc.), ao invés disso, você terá camuflagem total.',
          prerequisites: ['improvedStealth', 'concealedMovement'],
        },
      ],
    },
    {
      key: 'fringer',
      name: 'Árvore de Talentos do Improvisador',
      description: 'Você é especialmente habilidoso em "se virar" em mundos remotos e primitivos.',
      talents: [
        {
          id: 'haggler',
          name: 'Barganhador',
          description: 'Você pode fazer uma nova jogada de qualquer teste de Persuasão feito para barganhar. Entretanto, você precisa utilizar o resultado da nova jogada.',
          prerequisites: [],
        },
        {
          id: 'rigger',
          name: 'Engembrador',
          description: 'Você pode fazer uma nova jogada de qualquer teste de Mecânica feito para fazer uma Gambiarra, quando o intuito for o de reparos. Entretanto, você precisa utilizar o resultado da nova jogada.',
          prerequisites: [],
        },
        {
          id: 'longStride',
          name: 'Passo-Largo',
          description: 'Seu deslocamento aumenta em 2 quadrados se você estiver usando armadura leve ou nenhuma armadura. Se você tiver um deslocamento natural de vôo, escalada ou de natação, esse(s) aumenta(m) em 2 quadrados também. Você não pode se beneficiar deste talento se estiver usando armadura média ou pesada.',
          prerequisites: [],
        },
        {
          id: 'fringerSavvy',
          name: 'Sabedoria de Improvisador',
          description: 'Toda vez que você jogar um 20 natural em um teste de perícia durante um encontro, você recebe um Ponto da Força temporário. Se esse Ponto da Força não for usado antes do fim do encontro, ele é perdido.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'survivor',
      name: 'Árvore de Talentos do Sobrevivente',
      description: 'Como um explorador de lugares perigosos, você é treinado para reagir a perigos e em situações de dificuldade, assim como se guiar por terrenos difíceis.',
      talents: [
        {
          id: 'evasion',
          name: 'Evasão',
          description: 'Se você for atingido por um ataque em área, você receberá metade do dano se o ataque o acertar. Se o ataque errar, você não recebe dano. Este talento não se aplica a ataques em área feitos por veículos de tamanho Colossal ou maior.',
          prerequisites: [],
        },
        {
          id: 'extremeEffort',
          name: 'Esforço Extremo',
          description: 'Você pode utilizar duas ações rápidas para ganhar um bônus de +5 em um único teste de Força ou de uma perícia baseada em Força realizado nesta mesma rodada. Você deve gastar ambas as ações rápidas antes de fazer o teste.',
          prerequisites: [],
        },
        {
          id: 'runner',
          name: 'Corredor',
          description: 'Quando você usar uma ação de correr, você pode se mover a até cinco vezes o valor de seu deslocamento (ao invés do normal de quatro vezes seu deslocamento).',
          prerequisites: [],
        },
        {
          id: 'uncheckedMovement',
          name: 'Movimento Livre',
          description: 'Seu deslocamento não é reduzido por terrenos difíceis.',
          prerequisites: [],
        },
      ],
    },
  ],
};
