'use strict';

const CLASS_SCOUNDREL = {
  key: 'scoundrel',
  name: 'Malandro',
  description: 'Malandros são ladinos – bons, maus, e neutros – que vivem à margem da lei ou lutam contra ela para atingir algum objetivo maior. Eles podem vir de qualquer planeta ou região da galáxia. Muitos usam sua sagacidade e destreza para realizar tarefas e muitos contam com seu carisma como um plano b quando tudo o mais falha. Os malandros sobrevivem com ousadia, esperteza, trapaça e duas caras. Eles atuam por seu bom senso, por mentiras, trapaças, roubos, e até mesmo lutando quando se faz necessário.',
  hitDie: 6,
  startingHP: 18,
  trainedSkillsBase: 4,
  defenseBonus: { fort: 0, ref: 2, will: 1 },
  baseAttack: [0,1,2,3,3,4,5,6,6,7,8,9,9,10,11,11,12,12,13,15],
  classSkills: ['acrobatics','know1','know2','know3','know4','deception','stealth','initiative','mechanics','gatherInfo','perception','pilot','useComputer'],
  startingFeats: [
    'Tiro à Queima-Roupa',
    'Proficiência com Armas (Pistolas)',
    'Proficiência com Armas (Armas Simples)',
  ],
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Ataque em Movimento', 'Certeiro', 'Combate Veicular', 'Ataque Duplo', 'Foco em Perícia',
    'Defesas Aprimoradas', 'Proficiência com Armas (armas de combate corpo-a-corpo avançadas)',
    'Saque Rápido', 'Tiro Rápido', 'Tiro Preciso', 'Treinamento em Perícia', 'Trespassar', 'Trespassar Aprimorado',
  ],
  talentTrees: [
    {
      key: 'fortune',
      name: 'Árvore de Talentos da Sorte',
      description: 'Muitos malandros gostam de jogar com o destino colocando todas as cartas na mesa e confiando na sorte (ou na Força) para lhes trazer riquezas, fama, e sucesso.',
      talents: [
        {
          id: 'talented',
          name: 'Talentoso',
          description: 'Uma vez por dia, você pode refazer um teste de perícia e utilizar o melhor resultado obtido. Você pode escolher este talento mais de uma vez; cada vez que fizer, você poderá utilizá-lo uma vez por dia a mais.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'favoriteOfFortune',
          name: 'Favorecido pela Sorte',
          description: 'Toda vez que você obtiver um sucesso decisivo em um ataque corpo-a-corpo ou à distância (20 natural na jogada de ataque), você ganha uma ação padrão extra. Você precisa utilizar essa ação padrão extra antes do final deste turno, ou irá perdê-la.',
          prerequisites: ['talented'],
        },
        {
          id: 'luckyShot',
          name: 'Tiro de Sorte',
          description: 'Uma vez por dia, você pode refazer uma jogada de ataque e utilizar o melhor resultado obtido. Você pode escolher este talento mais de uma vez; cada vez que fizer, você poderá utilizá-la uma vez por dia a mais.',
          prerequisites: ['talented'],
          multiSelect: true,
        },
        {
          id: 'gambler',
          name: 'Apostador',
          description: 'Você recebe +2 de bônus de competência nos testes de Sabedoria quando apostar. Você pode escolher este talento mais de uma vez; cada vez que fizer, o bônus de competência aumenta em +2.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'foolsLuck',
          name: 'Sorte do Tolo',
          description: 'Utilizando uma ação padrão você pode gastar um Ponto da Força para ganhar um dos seguintes benefícios pelo resto do encontro: +1 de bônus de competência nas jogadas de ataque, +5 de bônus de competência nos testes de perícia, ou +1 de bônus de competência em todas as suas Defesas.',
          prerequisites: ['talented'],
        },
      ],
    },
    {
      key: 'misfortune',
      name: 'Árvore de Talentos da Má Sorte',
      description: 'Sua mãe sempre dizia que você só dava problema. Agora seus inimigos também pensam assim.',
      talents: [
        {
          id: 'sneakAttack',
          name: 'Ataque Furtivo',
          description: 'A qualquer momento que seu oponente estiver surpreendido ou, de outra maneira, tenha seu bônus de Destreza na Defesa de Reflexos negado, você causa 1d6 pontos de dano extra com um ataque corpo-a-corpo ou à distância bem sucedido. Você precisa estar a até 6 quadrados de distância do alvo para fazer um ataque furtivo com uma arma à distância. Você pode escolher este talento mais de uma vez; cada vez que o fizer, seu dano do ataque furtivo aumenta em +1d6 (até o máximo de +10d6).',
          prerequisites: [],
          multiSelect: true,
          maxSelect: 10,
        },
        {
          id: 'combatant',
          name: 'Combatente',
          description: 'Se você se mover ao menos 2 quadrados antes de seu ataque e terminar seu movimento em um quadrado diferente de onde o iniciou, você ganha um bônus de +1 nas jogadas de ataque até o começo de seu próximo turno.',
          prerequisites: [],
        },
        {
          id: 'sowConfusion',
          name: 'Semear Confusão',
          description: 'Ao gastar duas ações rápidas, você pode usar seu talento para causar problemas e instigar o caos para dilacerar seus inimigos. Até o começo de seu próximo turno, você anula todos os bônus de moral e intuição aplicados aos inimigos em sua linha de visão.',
          prerequisites: [],
        },
        {
          id: 'disconcert',
          name: 'Desconcertar',
          description: 'Utilizando uma ação padrão, você pode fazer ou falar algo que pegue seus inimigos com a guarda baixa. Todos os oponentes que estejam em sua linha de visão recebem -2 de penalidade em suas defesas até o começo do seu próximo turno. A penalidade é cancelada se a linha de visão com você for interrompida.',
          prerequisites: ['sowConfusion'],
        },
      ],
    },
    {
      key: 'slicer',
      name: 'Árvore de Talentos do Hacker',
      description: 'Você se move como um fantasma através da Holonet e pode encontrar brechas nos sistemas de mainframes inimigos e sistemas de computador com uma graça estonteante.',
      talents: [
        {
          id: 'lightningInvasion',
          name: 'Invasão Relâmpago',
          description: 'Você pode emitir um comando de rotina para um computador como uma ação rápida.',
          prerequisites: [],
        },
        {
          id: 'masterSlicer',
          name: 'Hacker Mestre',
          description: 'Você pode refazer qualquer teste de Usar Computador feito para aumentar o seu acesso a um computador, utilizando o melhor dos dois resultados.',
          prerequisites: ['lightningInvasion'],
        },
        {
          id: 'trace',
          name: 'Traçar',
          description: 'Você pode substituir sua perícia Usar Computador para qualquer teste de Obter Informação desde que tenha como acessar uma rede de computadores.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'spacer',
      name: 'Árvore de Talentos do Espaçonauta',
      description: 'Você vaga pelas rotas do espaço procurando riqueza, fama, aventuras, ou alguma coisa a mais. Você é realmente bom com veículos em geral.',
      talents: [
        {
          id: 'spaceAcclimated',
          name: 'Habituado com o Espaço',
          description: 'Você não sofre penalidades na jogada de ataque quando estiver em ambientes com baixa ou nenhuma gravidade e você ignora os efeitos debilitantes do enjôo espacial. Além disso, você é considerado proficiente em qualquer arma de espaçonave.',
          prerequisites: [],
        },
        {
          id: 'pirate',
          name: 'Pirata Espacial',
          description: 'Você recebe um bônus de +1 nas jogadas de ataque quando estiver a bordo de uma espaçonave. Este bônus se aplica aos ataques feitos com as armas de uma espaçonave assim como armas pessoais usadas a bordo de uma espaçonave.',
          prerequisites: ['spaceAcclimated'],
        },
        {
          id: 'starfighter',
          name: 'Guerreiro Estelar',
          description: 'Toda vez que você tirar um 20 natural em uma jogada de ataque realizada a bordo de uma espaçonave, você ganha um Ponto da Força temporário. Se esse Ponto da Força não for usado antes do fim do encontro, ele é perdido.',
          prerequisites: ['spaceAcclimated'],
        },
        {
          id: 'hyperaware',
          name: 'Hiperguiado',
          description: 'Uma vez por dia, quando estiver a bordo de uma espaçonave, você pode adicionar seu nível da classe Malandro como um bônus em uma única jogada de ataque, teste de perícia ou teste de habilidade. A decisão de adicionar esse bônus pode ser feita após ser conhecido o resultado da jogada ou do teste.',
          prerequisites: ['spaceAcclimated'],
        },
      ],
    },
  ],
};
