'use strict';

const CLASS_SCOUNDREL = {
  key: 'scoundrel',
  name: 'Scoundrel',
  hitDie: 6,
  startingHP: 18,
  trainedSkillsBase: 4,
  defenseBonus: { fort: 0, ref: 2, will: 1 },
  baseAttack: [0,1,2,3,3,4,5,6,6,7,8,9,9,10,11,11,12,12,13,15],
  classSkills: ['acrobatics','know1','know2','know3','know4','deception','stealth','initiative','mechanics','gatherInfo','perception','pilot','useComputer'],
  startingFeats: [
    'Point Blank Shot',
    'Weapon Proficiency (Pistols)',
    'Weapon Proficiency (Simple Weapons)',
  ],
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Attack in Movement', 'Accurate', 'Vehicular Combat', 'Double Attack', 'Skill Focus',
    'Improved Defenses', 'Weapon Proficiency (advanced melee)',
    'Quick Draw', 'Rapid Strike', 'Precise Shot', 'Skill Training', 'Trespass', 'Trespass Improved',
  ],
  talentTrees: [
    {
      key: 'fortune',
      name: 'Fortune Talent Tree',
      description: 'Many scoundrels like to gamble with life, trusting in luck (or the Force) to bring them riches, fame, and adventures.',
      talents: [
        {
          id: 'talented',
          name: 'Talented',
          description: 'Once per day, you may reroll any skill check and use whichever result is better. You can select this talent multiple times; each time, you can use it one more time per day.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'favoriteOfFortune',
          name: 'Favorite of Fortune',
          description: 'Once per day, when you score a decisive hit (natural 20 on attack roll) with a melee or ranged attack, gain an extra standard action that you may use before the end of the current turn. You must use this action or lose it.',
          prerequisites: ['talented'],
        },
        {
          id: 'luckyShot',
          name: 'Lucky Shot',
          description: 'Once per day, reroll an attack roll and use whichever result is better. You can select this talent multiple times; each time, you can use it one more time per day.',
          prerequisites: ['talented'],
          multiSelect: true,
        },
        {
          id: 'gambler',
          name: 'Gambler',
          description: 'You receive a +2 competence bonus on Wisdom checks when gambling. You can select this talent multiple times; each time, the bonus increases by +2.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'foolsLuck',
          name: "Fool's Luck",
          description: 'As a standard action, spend 1 Force Point to gain two beneficial results at the end of the encounter: +1 bonus to attack rolls, +5 bonus to skill checks, or +1 bonus to all Defenses (your choice for each). These bonuses last until the end of the encounter.',
          prerequisites: ['talented'],
        },
      ],
    },
    {
      key: 'misfortune',
      name: 'Misfortune Talent Tree',
      description: 'Your enemies think that you bring them bad luck. As your mother always said, you do.',
      talents: [
        {
          id: 'sneakAttack',
          name: 'Sneak Attack',
          description: 'When your opponent is surprised or is flat-footed (their Dexterity bonus to Reflex Defense is denied), you deal an extra 1d6 damage on a successful melee or ranged attack. You must be within 6 squares to use this talent at range. You can select this talent multiple times; each time, the damage increases by +1d6 (maximum +10d6).',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'combatant',
          name: 'Combatant',
          description: 'If you move at least 2 squares before ending your attack in a different square from where you started, you gain a +1 bonus to attack rolls until the start of your next turn.',
          prerequisites: [],
        },
        {
          id: 'sowConfusion',
          name: 'Sow Confusion',
          description: 'As both quick actions in your turn, you can confuse your enemies and instigate trouble among them. Until the start of your next turn, all enemies within your line of sight lose all morale bonuses and intuition bonuses applied to defenses.',
          prerequisites: [],
        },
        {
          id: 'disconcert',
          name: 'Disconcert',
          description: 'As a standard action, make all opponents who can see you suffer a -2 penalty to their defenses until the start of your next turn. The penalty is cancelled if line of sight is interrupted.',
          prerequisites: ['sowConfusion'],
        },
      ],
    },
    {
      key: 'slicer',
      name: 'Slicer Talent Tree',
      description: 'You move like a ghost through the HoloNet and can find breaches in enemy systems and computer networks with incredible ease.',
      talents: [
        {
          id: 'lightningInvasion',
          name: 'Lightning Invasion',
          description: 'You can issue a simple command to a computer (see page 79) as a quick action.',
          prerequisites: [],
        },
        {
          id: 'masterSlicer',
          name: 'Master Slicer',
          description: 'You can reroll any Use Computer check made to increase your access to a computer, taking the better of two results.',
          prerequisites: ['lightningInvasion'],
        },
        {
          id: 'trace',
          name: 'Trace',
          description: 'You can substitute your Use Computer skill for Gather Information whenever you have access to a HoloNet terminal.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'spacer',
      name: 'Spacer Talent Tree',
      description: 'You roam the space lanes seeking riches, fame, adventures, or just something more. You are genuinely skilled with vehicles.',
      talents: [
        {
          id: 'spaceAcclimated',
          name: 'Space Acclimated',
          description: 'You take no penalties on attack rolls aboard a ship with no gravity and ignore the debilitating effects of weightlessness (see Zero Gravity Environments, page 267). You are considered proficient with any spaceship weapon.',
          prerequisites: [],
        },
        {
          id: 'pirate',
          name: 'Pirate',
          description: 'You gain a +1 bonus to attack rolls when aboard a spaceship. This bonus applies to all attacks made with the spaceship\'s weapons as well as personal weapons used while aboard.',
          prerequisites: ['spaceAcclimated'],
        },
        {
          id: 'starfighter',
          name: 'Starfighter',
          description: 'Once per day, when you roll a natural 20 on an attack roll aboard a spaceship, you gain a temporary Force Point that must be used before the end of the encounter, otherwise it is lost.',
          prerequisites: ['spaceAcclimated'],
        },
        {
          id: 'hyperaware',
          name: 'Hyperaware',
          description: 'Once per day when aboard a spaceship, you can add your class level as a bonus to a single attack roll, skill check, or ability check. The decision to add this bonus can be made after the roll is known.',
          prerequisites: ['spaceAcclimated'],
        },
      ],
    },
  ],
};
