'use strict';

const CLASS_SCOUT = {
  key: 'scout',
  name: 'Scout',
  hitDie: 8,
  startingHP: 24,
  trainedSkillsBase: 5,
  defenseBonus: { fort: 1, ref: 2, will: 0 },
  baseAttack: [0,1,2,3,3,4,5,6,6,7,8,9,9,10,11,12,12,13,14,15],
  classSkills: ['ride','know1','know2','know3','know4','climb','stealth','initiative','mechanics','swim','perception','pilot','endurance','jump','survival'],
  startingFeats: [
    'Quick Recovery',
    'Weapon Proficiency (Pistols)',
    'Weapon Proficiency (Rifles)',
    'Weapon Proficiency (Simple Weapons)',
  ],
  startingFeatsNotes: {
    'Quick Recovery': 'Requires Constitution 13 and Endurance trained to gain this feat.',
  },
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Attack in Movement', 'Accurate', 'Vehicular Combat', 'Double Attack', 'Improved Defenses',
    'Skill Focus', 'Linguist', 'Mobility', 'Weapon Proficiency (advanced melee)',
    'Rapid Strike', 'Trespass', 'Trespass Improved', 'Precise Shot', 'Skill Training',
  ],
  talentTrees: [
    {
      key: 'awareness',
      name: 'Awareness Talent Tree',
      description: 'You are exceptionally skilled at perceiving things and avoiding dangerous situations.',
      talents: [
        {
          id: 'sharpenedSenses',
          name: 'Sharpened Senses',
          description: 'You may reroll any Perception check, but the result of the new roll must be accepted even if it is worse than the original.',
          prerequisites: [],
        },
        {
          id: 'improvedInitiative',
          name: 'Improved Initiative',
          description: 'You may reroll any Initiative check, but the result of the new roll must be accepted even if it is worse than the original.',
          prerequisites: ['sharpenedSenses'],
        },
        {
          id: 'exceptionalDodgeI',
          name: 'Exceptional Dodge I',
          description: 'You retain your Dexterity bonus to Reflex Defense even when flanked or targeted by a hidden enemy. You also retain it when immobilized.',
          prerequisites: ['sharpenedSenses', 'improvedInitiative'],
        },
        {
          id: 'exceptionalDodgeII',
          name: 'Exceptional Dodge II',
          description: 'You cannot be flanked; you can react to opponents on both sides as easily as a single attacker.',
          prerequisites: ['sharpenedSenses', 'improvedInitiative', 'exceptionalDodgeI'],
        },
        {
          id: 'experiencedTracker',
          name: 'Experienced Tracker',
          description: 'You take no penalties on Survival checks made to track in your current terrain type. Additionally, you take a -5 penalty (instead of the normal -5) on Survival checks to track when moving at your normal speed.',
          prerequisites: ['sharpenedSenses'],
        },
      ],
    },
    {
      key: 'camouflage',
      name: 'Camouflage Talent Tree',
      description: 'You learn how to blend in with your environment seamlessly.',
      talents: [
        {
          id: 'improvedStealth',
          name: 'Improved Stealth',
          description: 'You may reroll any Stealth check, but the result of the new roll must be accepted even if it is worse than the original.',
          prerequisites: [],
        },
        {
          id: 'concealedMovement',
          name: 'Concealed Movement',
          description: 'You take no penalty to Stealth checks when moving at your normal speed. You take a -5 penalty (instead of the normal penalty) on Stealth checks when moving faster than your speed.',
          prerequisites: [],
        },
        {
          id: 'sharpshooting',
          name: 'Sharpshooting',
          description: 'You take no penalty on attack rolls when firing at targets with partial concealment (but not total concealment).',
          prerequisites: ['improvedStealth'],
        },
        {
          id: 'totalCamouflage',
          name: 'Total Camouflage',
          description: 'In any situation in which you would normally gain concealment (from terrain, low light, etc.), you instead gain total concealment.',
          prerequisites: ['improvedStealth', 'concealedMovement'],
        },
      ],
    },
    {
      key: 'fringer',
      name: 'Fringer Talent Tree',
      description: 'You are especially skilled at "making do" in remote and primitive environments.',
      talents: [
        {
          id: 'haggler',
          name: 'Haggler',
          description: 'You may reroll any Persuasion check made to bargain; you must use the result of the new check even if it is worse.',
          prerequisites: [],
        },
        {
          id: 'rigger',
          name: 'Rigger',
          description: 'You may reroll any Mechanics check made to rig a device (see Mechanics skill, page 68). You must use the result of the new check even if it is worse.',
          prerequisites: [],
        },
        {
          id: 'longStride',
          name: 'Long Stride',
          description: 'Your speed increases by 2 squares when wearing light or no armor. If you have a natural fly, climb, or swim speed, those speeds increase by 2 as well. You cannot benefit from this talent when wearing medium or heavy armor.',
          prerequisites: [],
        },
        {
          id: 'fringerSavvy',
          name: "Fringer's Savvy",
          description: 'Once per day, when you roll a natural 20 on any skill check during an encounter, you gain a temporary Force Point. If you do not use this Force Point before the end of the encounter, it is lost.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'survivor',
      name: 'Survivor Talent Tree',
      description: 'As an explorer of dangerous places, you are trained to react to danger and cope in difficult terrain.',
      talents: [
        {
          id: 'evasion',
          name: 'Evasion',
          description: 'When you are hit by an area attack, you take half damage. If the attack misses you, you take no damage. This talent does not apply to area attacks made by vehicles of Colossal size or larger.',
          prerequisites: [],
        },
        {
          id: 'extremeEffort',
          name: 'Extreme Effort',
          description: 'As both quick actions in a round, gain a +5 bonus to a single Force test or a Strength-based skill check performed in that same round. You must spend both quick actions before making the check.',
          prerequisites: [],
        },
        {
          id: 'runner',
          name: 'Runner',
          description: 'When you take the run action, you can move up to 5 times your speed (instead of the normal 4 times your speed).',
          prerequisites: [],
        },
        {
          id: 'uncheckedMovement',
          name: 'Unchecked Movement',
          description: 'Your speed is not reduced by difficult terrain (see Difficult Terrain, page 167).',
          prerequisites: [],
        },
      ],
    },
  ],
};
