'use strict';

const CLASS_SOLDIER = {
  key: 'soldier',
  name: 'Soldier',
  hitDie: 10,
  startingHP: 30,
  trainedSkillsBase: 3,
  defenseBonus: { fort: 2, ref: 1, will: 0 },
  baseAttack: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
  classSkills: ['know1','climb','initiative','mechanics','swim','perception','pilot','endurance','jump','treatInjury','useComputer'],
  startingFeats: [
    'Weapon Proficiency (Simple Weapons)',
    'Weapon Proficiency (Pistols)',
    'Weapon Proficiency (Rifles)',
    'Armor Proficiency (Light)',
    'Armor Proficiency (Medium)',
  ],
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Throw', 'Martial Arts I', 'Martial Arts II', 'Martial Arts III', 'Ranged Attack',
    'Double Attack', 'Attack in Movement', 'Power Attack', 'Quick Draw', 'Triple Attack',
    'Tripled Critical', 'Defender-in-Melee', 'Improved Disarm', 'Acrobatic Attack',
    'Weapon Focus', 'Weapon Specialization', 'Point Blank Shot', 'Accurate', 'Vehicular Combat',
    'Improved Defenses', 'Quick Recovery', 'Reflexes in Combat', 'Rapid Strike',
    'Precise Shot', 'Trespass', 'Trespass Improved', 'Vigoroso',
  ],
  talentTrees: [
    {
      key: 'armorSpecialist',
      name: 'Armor Specialist Talent Tree',
      description: 'You know how to maximize the benefits of wearing armor while minimizing or eliminating some of its disadvantages.',
      talents: [
        {
          id: 'armoredDefense',
          name: 'Armored Defense',
          description: 'When calculating your Reflex Defense, you may add your heroic level or your armor bonus, whichever is greater. You must be proficient with the armor you are wearing to gain this benefit.',
          prerequisites: [],
        },
        {
          id: 'armoredDefenseImproved',
          name: 'Armored Defense (Improved)',
          description: 'When calculating your Reflex Defense, add your heroic level plus half your armor bonus (rounded down) or your armor bonus, whichever is greater. You must be proficient with the armor you are wearing.',
          prerequisites: ['armoredDefense'],
        },
        {
          id: 'ironWill',
          name: 'Armored Fighter',
          description: 'Your armor does not reduce your speed or the distance you can move when running. You must be proficient with the armor you are wearing to gain this benefit.',
          prerequisites: ['armoredDefense'],
        },
        {
          id: 'secondSkin',
          name: 'Second Skin',
          description: 'When wearing armor with which you are proficient, your armor\'s Reflex Defense bonus and Fortitude Defense bonus each increase by +1.',
          prerequisites: ['armoredDefense'],
        },
      ],
    },
    {
      key: 'brawler',
      name: 'Brawler Talent Tree',
      description: 'You like to get up close with your enemies and engage them in hand-to-hand combat.',
      talents: [
        {
          id: 'hardHit',
          name: 'Hard Hit',
          description: 'You gain a +1 bonus to damage with melee attacks.',
          prerequisites: [],
        },
        {
          id: 'staggeringAttack',
          name: 'Staggering Attack',
          description: 'When you deal damage with a melee attack equal to or exceeding the target\'s Damage Threshold, that opponent falls 1 additional step on the condition track beyond any other effects.',
          prerequisites: ['hardHit'],
        },
        {
          id: 'gunbutt',
          name: 'Gunbutt',
          description: 'You can use a ranged weapon as a melee weapon without penalty on attack rolls. The ranged weapon is treated in all respects as a club (improvised melee weapon).',
          prerequisites: [],
        },
        {
          id: 'grapplingSpecialist',
          name: 'Grappling Specialist',
          description: 'You gain a +2 competence bonus on Grapple checks (see page 160).',
          prerequisites: [],
        },
        {
          id: 'unbalanceOpponent',
          name: 'Unbalance Opponent',
          description: 'You are skilled at throwing your opponents off balance in hand-to-hand combat. During your action, you may swap your attack bonus for a +1 bonus to all attacks against that opponent made by your allies this round.',
          prerequisites: ['grapplingSpecialist'],
        },
      ],
    },
    {
      key: 'commando',
      name: 'Commando Talent Tree',
      description: 'You employ advanced combat tactics to defeat your enemies quickly, cover your allies, and overcome any challenge.',
      talents: [
        {
          id: 'battleAnalysis',
          name: 'Battle Analysis',
          description: 'As a quick action, make a Knowledge (tactics) check (DC 15). If successful, you know which allies and opponents in your line of sight have their hit points reduced to half or less of the total value.',
          prerequisites: [],
        },
        {
          id: 'coveringFire',
          name: 'Covering Fire',
          description: 'When you make a ranged attack, if the attack hits, all allies within line of sight gain a +1 bonus to Reflex Defense until the start of your next turn. Allies within range at the start of your next turn lose this benefit.',
          prerequisites: ['battleAnalysis'],
        },
        {
          id: 'demolitions',
          name: 'Demolitions',
          description: 'You can place an explosive device as a standard action using the Mechanics skill. When the explosion occurs, it deals +2 damage. You can select this talent multiple times; each time, the damage increases by +2 (the effects stack).',
          prerequisites: ['battleAnalysis'],
          multiSelect: true,
        },
        {
          id: 'interpose',
          name: 'Interpose',
          description: 'Once per round, you may use a quick action to protect an adjacent ally, receiving the damage and effects of any attack targeting that ally until the start of your next turn. All attacks against the protected ally are instead directed at you.',
          prerequisites: [],
          requiresFeat: 'Skill Training (Initiative)',
        },
        {
          id: 'indomitable',
          name: 'Indomitable',
          description: 'Once per day as a quick action, move up 5 steps on the condition track. This does not remove any persistent conditions. You can select this talent multiple times; each time, you can use it one more time per day.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'drawFire',
          name: 'Draw Fire',
          description: 'As a quick action, distract opponents and convince them that you are the easiest (or most dangerous) target. Make a Persuasion check and compare the result with the Will Defense of all enemies within your line of sight. Enemies whose Will Defense is exceeded by your check cannot attack any character except you until the start of your next turn.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'weaponSpecialist',
      name: 'Weapon Specialist Talent Tree',
      description: 'You are highly trained in the use of specific weapons.',
      talents: [
        {
          id: 'devastatingAttack',
          name: 'Devastating Attack',
          description: 'Choose a single exotic weapon or weapon group. Whenever you score a successful hit using that weapon, treat the target\'s Damage Threshold as if it were 5 points lower when determining the result of your attack. You can select this talent multiple times; each time it applies to a different weapon or group.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'piercingAttack',
          name: 'Piercing Attack',
          description: 'Choose a single exotic weapon or weapon group. Whenever you score a successful hit using that weapon, treat the target\'s damage reduction as if it were 5 points lower when determining the result of your attack. You can select this talent multiple times; each time it applies to a different weapon or group.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'weaponSpecialization',
          name: 'Weapon Specialization',
          description: 'Choose a single exotic weapon or weapon group. You receive a +2 bonus on damage rolls made using that weapon. You can select this talent multiple times; each time it applies to a different weapon or group.',
          prerequisites: [],
          requiresFeat: 'Weapon Focus (chosen weapon or group)',
          multiSelect: true,
        },
      ],
    },
  ],
};
