'use strict';

export const CLASS_SOLDIER = {
  key: 'soldier',
  name: 'Soldado',
  description: 'Os soldados combinam disciplina com habilidades marciais para se tornarem os melhores combatentes na galáxia. Soldados podem ser leais defensores daqueles em necessidade, saqueadores cruéis, ou bravos aventureiros. Também podem ser mercenários, campeões da nobreza, ou assassinos de coração frio. Eles lutam por glória, por honra, para fazer a coisa certa, para ganhar poder, para adquirir riquezas ou simplesmente pela emoção da batalha.',
  hitDie: 10,
  startingHP: 30,
  trainedSkillsBase: 3,
  defenseBonus: { fort: 2, ref: 1, will: 0 },
  baseAttack: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
  classSkills: ['know1','climb','initiative','mechanics','swim','perception','pilot','endurance','jump','treatInjury','useComputer'],
  startingFeats: [
    'Proficiência com Armas (Armas Simples)',
    'Proficiência com Armas (Pistolas)',
    'Proficiência com Armas (Rifles)',
    'Proficiência com Armaduras (leves)',
    'Proficiência com Armaduras (médias)',
  ],
  levelFeatures: {
    1:  ['defenseBonus', 'startingFeats', 'talent'],
    2:  ['bonusFeat'],
    3:  ['talent'],
    4:  ['bonusFeat'],
    5:  ['talent'],
    6:  ['bonusFeat'],
    7:  ['talent'],
    8:  ['bonusFeat'],
    9:  ['talent'],
    10: ['bonusFeat'],
    11: ['talent'],
    12: ['bonusFeat'],
    13: ['talent'],
    14: ['bonusFeat'],
    15: ['talent'],
    16: ['bonusFeat'],
    17: ['talent'],
    18: ['bonusFeat'],
    19: ['talent'],
    20: ['bonusFeat'],
  },
  bonusFeatList: [
    'Arremessar', 'Artes Marciais I', 'Artes Marciais II', 'Artes Marciais III', 'Ataque Coordenado',
    'Ataque Duplo', 'Ataque em Movimento', 'Ataque Poderoso', 'Ataque Rápido', 'Ataque Triplo',
    'Certeiro', 'Combate Veicular', 'Crítico Triplicado', 'Defender-se em Corpo-a-Corpo', 'Derrubar',
    'Desarme Aprimorado',
    'Foco em Arma (Armas Simples)', 'Foco em Arma (Pistolas)', 'Foco em Arma (Rifles)',
    'Foco em Arma (armas de combate corpo-a-corpo avançadas)', 'Foco em Arma (armas pesadas)',
    'Foco em Arma (arma exótica)',
    'Foco em Perícia', 'Imobilizar', 'Maestria com Duas Armas I',
    'Maestria com Duas Armas II', 'Maestria com Duas Armas III', 'Proficiência com Armaduras (pesadas)',
    'Proficiência com Armas (armas de combate corpo-a-corpo avançadas)', 'Proficiência com Armas (armas pesadas)',
    'Recuperação Rápida', 'Reflexos em Combate', 'Saque Rápido', 'Tiro à Queima-Roupa', 'Tiro Preciso',
    'Tiro Rápido', 'Treinamento em Perícia', 'Trespassar', 'Trespassar Aprimorado', 'Vigoroso',
  ],
  talentTrees: [
    {
      key: 'armorSpecialist',
      name: 'Árvore de Talentos do Especialista em Armaduras',
      description: 'Você pode maximizar os benefícios por usar armadura ao mesmo tempo em que reduz ou elimina algumas de suas desvantagens.',
      talents: [
        {
          id: 'armoredDefense',
          name: 'Defesa Blindada',
          description: 'Quando estiver calculando sua Defesa de Reflexos, você pode somar seu nível heróico ou seu bônus de armadura, o que for maior. Você precisa ser proficiente com a armadura que estiver usando para receber esse benefício.',
          prerequisites: [],
        },
        {
          id: 'armoredDefenseImproved',
          name: 'Defesa Blindada Aprimorada',
          description: 'Quando estiver calculando sua Defesa de Reflexos, você pode somar seu nível heróico mais metade de seu bônus de armadura (arredondado para baixo) ou seu bônus de armadura, o que for maior. Você precisa ser proficiente com a armadura que estiver usando para receber esse benefício.',
          prerequisites: ['armoredDefense'],
        },
        {
          id: 'ironWill',
          name: 'Couraçado',
          description: 'Sua armadura não reduzirá seu deslocamento ou a distância que pode se mover quando estiver correndo. Você precisa ser proficiente com a armadura que estiver usando para receber esse benefício.',
          prerequisites: ['armoredDefense'],
        },
        {
          id: 'secondSkin',
          name: 'Segunda Pele',
          description: 'Quando estiver usando uma armadura na qual seja proficiente, seus bônus de armadura em sua Defesa de Reflexos e bônus de equipamento em sua Defesa de Fortitude aumentam em +1.',
          prerequisites: ['armoredDefense'],
        },
      ],
    },
    {
      key: 'brawler',
      name: 'Árvore de Talentos do Lutador',
      description: 'Você gosta de lutar próximo de seus inimigos e se engaja em combates corpo-a-corpo com eles.',
      talents: [
        {
          id: 'hardHit',
          name: 'Golpe Duro',
          description: 'Você causa +1 ponto de dano com ataques corpo-a-corpo.',
          prerequisites: [],
        },
        {
          id: 'staggeringAttack',
          name: 'Ataque Atordoante',
          description: 'Quando causar dano num oponente com um ataque corpo-a-corpo, esse oponente cai um passo adicional em seu marcador de condição se sua jogada de dano igualar ou exceder o Limite de Dano do alvo.',
          prerequisites: ['hardHit'],
        },
        {
          id: 'gunbutt',
          name: 'Coronhada',
          description: 'Você pode usar uma arma de combate à distância como uma arma de combate corpo-a-corpo sem receber penalidade na jogada de ataque. A arma será tratada, em todos os aspectos, como um porrete. Se você estiver usando um rifle com uma baioneta montada ou vibrobaioneta, você pode manejar essa arma como uma arma dupla.',
          prerequisites: [],
        },
        {
          id: 'grapplingSpecialist',
          name: 'Especialista em Imobilização',
          description: 'Você ganha +2 de bônus de competência em ataques de Prender.',
          prerequisites: [],
        },
        {
          id: 'unbalanceOpponent',
          name: 'Desequilibrar Oponente',
          description: 'Você é habilidoso em deixar seus oponentes desequilibrados em combate corpo-a-corpo. Durante sua ação você deve escolher um oponente não mais que uma categoria de tamanho maior ou menor que você. Esse oponente não recebe seu bônus de Força nas jogadas de ataque quando estiver atacando você. O modificador de Força do oponente ainda se aplica ao dano, normalmente. Você pode escolher um novo oponente em seu próximo turno.',
          prerequisites: ['grapplingSpecialist'],
        },
      ],
    },
    {
      key: 'commando',
      name: 'Árvore de Talentos do Comando',
      description: 'Você emprega táticas avançadas de combate para derrotar inimigos rapidamente, cobrir seus companheiros, e resistir a quaisquer desafios que atravessarem seu caminho.',
      talents: [
        {
          id: 'battleAnalysis',
          name: 'Análise da Batalha',
          description: 'Utilizando uma ação rápida, você pode fazer um teste de Conhecimento (Táticas) contra um ND 15. Se o teste for bem sucedido você sabe quais aliados e oponentes em sua linha de visão tiveram seus pontos de vida reduzidos à metade do valor total.',
          prerequisites: [],
        },
        {
          id: 'coveringFire',
          name: 'Tiro de Cobertura',
          description: 'Quando você fizer uma jogada de ataque à distância, todos os aliados que estiverem a 6 quadrados de você quando o ataque for feito recebem +1 de bônus em sua Defesa de Reflexos até o começo de seu próximo turno. Aliados dentro do alcance não precisam estar em sua linha de visão para receber o bônus.',
          prerequisites: ['battleAnalysis'],
        },
        {
          id: 'demolitions',
          name: 'Demolidor',
          description: 'Quando você usar a perícia Mecânica para colocar um dispositivo explosivo, a explosão causa +2 dados de dano. Você pode pegar este talento várias vezes; seus efeitos se acumulam.',
          prerequisites: ['battleAnalysis'],
          multiSelect: true,
        },
        {
          id: 'interpose',
          name: 'Interpor-se',
          description: 'Uma vez por rodada, você pode gastar uma ação rápida para proteger um único aliado adjacente de ataques, recebendo o dano e sofrendo seus efeitos ao invés de seu aliado. Até o começo do seu próximo turno, qualquer ataque feito contra o aliado protegido terá como alvo você ao invés dele. Você pode decidir não proteger contra um determinado ataque o aliado protegido, contando que a decisão seja dita antes que a jogada de ataque seja feita.',
          prerequisites: [],
          requiresFeat: 'Treinamento em Perícia (Iniciativa)',
        },
        {
          id: 'indomitable',
          name: 'Indomável',
          description: 'Uma vez por dia, utilizando uma ação rápida, você pode subir 5 passos em seu marcador de condição. Isso não remove nenhuma condição persistente que esteja afetando você. Você pode selecionar esse talento mais de uma vez. Cada vez que o fizer, você poderá usá-lo uma vez a mais por dia.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'drawFire',
          name: 'Atrair Disparos',
          description: 'Você pode distrair oponentes e convencê-los que você é o alvo mais fácil (ou mais perigoso) na área. Utilizando uma ação rápida faça um teste de Persuasão e compare o resultado com a Defesa de Vontade de todos os oponentes que puderem vê-lo. Se o resultado do teste exceder a Defesa de Vontade do oponente, esse oponente não poderá atacar qualquer personagem a até 6 quadrados de você até o começo do seu próximo turno.',
          prerequisites: [],
        },
      ],
    },
    {
      key: 'weaponSpecialist',
      name: 'Árvore de Talentos do Especialista em Armas',
      description: 'Você é altamente treinado em usar armas específicas.',
      talents: [
        {
          id: 'devastatingAttack',
          name: 'Ataque Devastador',
          description: 'Escolha uma única arma exótica ou um grupo de armas em que seja proficiente. Toda vez que você fizer um ataque bem sucedido contra um alvo usando essa arma, você trata o Limite de Dano de seu alvo como se fosse 5 pontos mais baixo quando estiver determinando o resultado do seu ataque. Você pode escolher este talento mais de uma vez; cada vez que o fizer, se aplica a uma arma exótica ou grupo de armas diferente.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'piercingAttack',
          name: 'Ataque Penetrante',
          description: 'Escolha uma única arma exótica ou um grupo de armas em que seja proficiente. Toda vez que você fizer um ataque bem sucedido contra um alvo usando essa arma, você trata a redução de dano de seu alvo como se fosse 5 pontos mais baixo quando estiver determinando o resultado do seu ataque. Você pode escolher este talento mais de uma vez; cada vez que o fizer, se aplica a uma arma exótica ou grupo de armas diferente.',
          prerequisites: [],
          multiSelect: true,
        },
        {
          id: 'weaponSpecialization',
          name: 'Especialização em Arma',
          description: 'Escolha uma única arma exótica ou um grupo de armas em que seja proficiente. Você recebe um bônus de +2 nas jogadas de dano com essas armas. Você pode escolher este talento mais de uma vez; cada vez que o fizer, se aplica a uma arma exótica ou grupo de armas diferente.',
          prerequisites: [],
          requiresFeat: 'Foco em Arma (arma exótica ou grupo de armas escolhido)',
          multiSelect: true,
        },
      ],
    },
  ],
};
